server:
  servlet:
    context-path: /weather

owm:
  api:
    key: 2217739da79d7ad63b2c2cbc0ec31d1f

history:
  url: http://localhost:8081/weather-history/record

logging:
  level:
    root: info

spring:
  cache:
    cache-names: weather_forecasts
    caffeine:
      spec: expireAfterWrite=30m