server:
  servlet:
    context-path: /weather

owm:
  api:
    key: 2217739da79d7ad63b2c2cbc0ec31d1f

history:
  url: http://weather-history-app:8080/weather-history/records

spring:
  cache:
    cache-names: weather_forecasts
    caffeine:
      spec: expireAfterWrite=30m
