server:
  servlet:
    context-path: /weather
    application-display-name: weather-service

owm:
  api:
    key: 2217739da79d7ad63b2c2cbc0ec31d1f

history:
  url: http://weather-history-service:8080/weather-history/records

logging:
  level:
    root: info

spring:
  cache:
    cache-names: weather_forecasts
    caffeine:
      spec: expireAfterWrite=30m
