FROM bellsoft/liberica-openjdk-alpine:17

WORKDIR /app

COPY ../gradle gradle
COPY ../gradlew settings.gradle.kts build.gradle.kts ./
COPY ../src ./src

RUN chmod +x gradlew && ./gradlew assemble

CMD ./gradlew bootRun