version: '2.4'

services:
  weather-app:
    image: weather-app:1.0
    depends_on:
      weather-history-service:
        condition: service_started
    environment:
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  weather-history-service:
    image: weather-requests-history-service:2.0
    depends_on:
      postgres:
        condition: service_started
    environment:
      SERVER_PORT: 8080
    ports:
      - "8081:8080"

  weather-frontend:
    image: weather-frontend:1.0
    depends_on:
      weather-app:
        condition: service_started
    environment:
      SERVER_PORT: 8080
    ports:
      - "80:8080"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=weather
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      postgres:
        condition: service_started
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"