version: '2.4'

services:
  weather-app:
    image: weather-app:0.0.1
    depends_on:
      weather-history-service:
        condition: service_started
    environment:
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  weather-history-service:
    image: weather-requests-history-service:0.0.1
    environment:
      SERVER_PORT: 8080
    ports:
      - "8081:8080"

  weather-front:
    image: weather-frontend:0.0.1
    depends_on:
      weather-app:
        condition: service_started
    environment:
      SERVER_PORT: 8080
    ports:
      - "80:8080"