version: '2.4'

services:
  weather-app:
    image: disterru/weather-app
    container_name: weather-app
    depends_on:
      weather-history-app:
        condition: service_started
    environment:
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  weather-history-app:
    image: disterru/weather-history-app
    container_name: weather-history-app
    depends_on:
      postgres:
        condition: service_started
    environment:
      SERVER_PORT: 8080
    ports:
      - "8081:8080"

  weather-frontend:
    image: disterru/weather-frontend
    container_name: weather-frontend
    depends_on:
      weather-app:
        condition: service_started
    environment:
      SERVER_PORT: 8080
    ports:
      - "80:8080"

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=weather
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      postgres:
        condition: service_started
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"